apiVersion: apps/v1
kind: Deployment
metadata:
  name: containers-data-exchange
  labels:
    app: exchange
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exchange
  template:
    metadata:
      labels:
        app: exchange
    spec:
      containers:
      - name: busybox
        image: busybox:1.28
        command: ['sh', '-c', 'while true; do echo Success! >> /tmp/exchange/data.txt; sleep 5; done']
        volumeMounts:
        - name: vol
          mountPath: /tmp/exchange/pv

 
      - name: network-multitool
        image: wbitt/network-multitool
        env:
          - name: HTTP_PORT
            value: "8080"
        volumeMounts:
        - name: vol
          mountPath: /tmp/exchange/pv

      volumes:
      - name: vol
        # hostPath:
        #   path: /tmp/exchange
        persistentVolumeClaim:
          claimName: pvc
